version: "3"
services:
  db:
    image: postgres:11
    restart: always
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: s1
    ports:
      - "5432:5432"
